ssh_keys:
- "{{lookup('file', './ssh_keys/drtom')}}"

# no point in using ntp for a virtual machine
ntp_enabled: False


# comes handy, however can be a big security hole
nrepl_bind_address: 0.0.0.0

# comes handy, however it is a security problem
executor_nrepl_enabled: True

lein_service_xmx_value: 256M
user_interface_xmx_value: 500M

