- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: 
    - firefox
  when: ansible_distribution != 'Debian'



# firefox on debian 

- shell: apt-key adv --recv-keys --keyserver keyserver.ubuntu.com C1289A29
  when: ansible_distribution == 'Debian'

- apt_repository:  repo="deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main"
  when: ansible_distribution == 'Debian'

- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: 
    - firefox-mozilla-build
  when: ansible_distribution == 'Debian'



- lineinfile:
    line: "{{item}},"
    dest: /etc/cider-ci/traits.txt
    create: yes
    state: present
  with_items:
    - firefox
