-  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
   with_items:
    - curl

- lineinfile:
    line: "{{item}},"
    dest: /etc/cider-ci/traits.txt
    create: yes
    state: present
  with_items:
    - curl
