-  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
   with_items: 
    - tightvncserver
    - x11vnc 
    - fluxbox 

- file: path="~{{user}}/.vnc" 
        state=directory
        owner={{user}}
        group={{user}}
        mode=0755

- template: src=vnc_xstartup
            dest={{user_home}}/.vnc/xstartup
            owner={{user}}
            mode=0755

- copy: src=vnc_passwd
        dest={{user_home}}/.vnc/passwd
        owner={{user}}
        group={{user}}
        mode=0600

- lineinfile:
    line: "{{item}},"
    dest: /etc/cider-ci/traits.txt
    create: yes
    state: present
  with_items:
    - tightvnc
    - x11vnc
    - fluxbox

