### offline ###################################################################

- template: >
    src=offline.apache.conf
    dest=/etc/apache2/sites-available/offline.conf 
    mode=0755

- command: a2ensite offline
  when: not reverse_proxy_enabled

- command: a2dissite offline
  when: reverse_proxy_enabled

- template: >
    src=offline_https.apache.conf
    dest=/etc/apache2/sites-available/offline_https.conf 
    mode=0755

- command: a2ensite offline_https
  when: not reverse_proxy_enabled

- command: a2dissite offline_https
  when: reverse_proxy_enabled



### shared site  ##############################################################

- file: path=/etc/apache2/shared
        state=directory
        mode=0755

- template: >
    src=shared-site.apache.conf
    dest=/etc/apache2/shared/cider-ci_site.conf 
    mode=0644


### http site #################################################################

- template: >
    src=site.apache.conf
    dest=/etc/apache2/sites-available/cider-ci.conf 
    mode=0755

- command: a2ensite cider-ci
  when: reverse_proxy_enabled

- command: a2dissite cider-ci
  when: not reverse_proxy_enabled


### https site ################################################################

- template: >
    src=site_https.apache.conf
    dest=/etc/apache2/sites-available/cider-ci_https.conf 
    mode=0755
  register: reverse_proxy_https_site

- command: a2ensite cider-ci_https
  when: reverse_proxy_enabled

- command: a2dissite cider-ci_https
  when: not reverse_proxy_enabled

### reload ####################################################################

- service: name=apache2
           state=reloaded

