# user with bash shell

- apt: 
    pkg: sudo 
    state: latest 
    update_cache: yes 
    cache_valid_time: 3600

- name: Add the user {{user}}
  user: name={{user}}
        generate_ssh_key=yes
        system=no
        shell=/bin/bash

- name: Allow the exec-user to sudo itself
  template: 
    src: sudo
    dest: "/etc/sudoers.d/{{user}}"

# ~/.bash_login.d gets sourced

- file: path="~{{user}}/.bash_login.d" 
        state=directory
        owner={{user}}
        group={{user}}
        mode=0755

- template: src=keep
            dest="~{{user}}/.bash_login.d/keep" 
            owner={{user}} group={{user}} mode=0644

- lineinfile: line='if [[ -d ~/.bash_login.d ]]; then for file in ~/.bash_login.d/* ;do source "$file"; done; fi'
              state=present
              create=yes
              owner={{user}}
              mode=0644
              dest=~{{user}}/.bash_login

### .bash_profile sources .bash_login

- lineinfile: line='if [[ -f ~/.bash_login ]]; then source ~/.bash_login; fi'
              state=present
              dest=~{{user}}/.bash_profile
              owner={{user}}
              mode=0644
              create=yes

- lineinfile: line='if [[ -d ~/.bash_login.d ]]; then for file in ~/.bash_login.d/* ;do source "$file"; done; fi'
              state=absent
              dest=~{{user}}/.bash_profile
              owner={{user}}
              mode=0644
              create=yes

### .bash_login 

- lineinfile: line='if [[ -d ~/.bash_login.d ]]; then for file in ~/.bash_login.d/* ;do source "$file"; done; fi'
              state=present
              dest=~{{user}}/.bash_login
              owner={{user}}
              mode=0644
              create=yes


