
-  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
   with_items: 
    - fluxbox 
    - imagemagick
    - libimage-exiftool-perl
    - nodejs
    - npm
    - tightvncserver
    - x11vnc 


- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: 
    - firefox
  when: ansible_distribution_release != 'wheezy'


# firefox on debian wheezy

- shell: apt-key adv --recv-keys --keyserver keyserver.ubuntu.com C1289A29
  when: ansible_distribution_release == 'wheezy'

#- apt_key: >
#    id=C1289A29 
#    keyserver=http://keyserver.ubuntu.com 
#  when: ansible_distribution_release == 'wheezy'

- apt_repository:  repo="deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main"
  when: ansible_distribution_release == 'wheezy'


- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: 
    - firefox-mozilla-build
  when: ansible_distribution_release == 'wheezy'

