### MySQL

- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - libmysqlclient-dev
    - mysql-client-5.5
    - mysql-server-5.5
    - python-configparser
    - python-mysqldb

- mysql_user: name={{executor_execution_user | truncate(16,'') }}
              password={{executor_execution_user}}
              priv=*.*:ALL
              state=present

- template: src=mysql_env
            dest=~{{executor_execution_user}}/.bash_login.d/mysql_env
            owner={{executor_execution_user}}
            mode=0755

- lineinfile:
    line: "{{item}},"
    dest: /etc/cider-ci/traits.txt
    create: yes
    state: absent
  with_items:
    - mariadb

- lineinfile:
    line: "{{item}},"
    dest: /etc/cider-ci/traits.txt
    create: yes
    state: present
  with_items:
    - mysql
    - mysql-5.5

